### ISSUE TITLE
pypi version completely useless

### ISSUE THREAD

**Issue by jlec** [rasbt/biopandas#1]
The pypi tarball has major packaging problems. Simply commands like

```python
from biopandas.pdb import PandasPDB
```
Do not work as no submodule is included

```shell
$ find /usr/local/lib/python3.4/site-packages/biopandas
/usr/local/lib/python3.4/site-packages/biopandas
/usr/local/lib/python3.4/site-packages/biopandas/__init__.py
/usr/local/lib/python3.4/site-packages/biopandas/__pycache__
/usr/local/lib/python3.4/site-packages/biopandas/__pycache__/__init__.cpython-34.pyc
```

**Comment by rasbt** [comment]
Thanks for letting me know. I just added the submodule structure at the very end and simply forgot to update the setup.py file. Should be fixed now (needed to bumb the version number for that so that `pip install biopandas --upgrade` should install v 1.4.0).

**Comment by jlec** [comment]
Thanks that works.
