### ISSUE TITLE
Docs tutorials & API reference out of date

### ISSUE THREAD

**Issue by a-r-j** [rasbt/biopandas#106]
#### Describe the documentation issue
It looks like the tutorial and API reference in the docs haven't been updated since 0.3.0 (e.g. https://rasbt.github.io/biopandas/api_subpackages/biopandas.pdb/)

Looking at the docs folders the source notebooks have been updated, but presumably these are translated into markdown by the docs builder (not sure what the exact setup is) and these markdown files haven't been regenerated.

**Comment by rasbt** [comment]
Thanks for the note. Not sure how that happened since it is part of my "new version" push workflow. It should be fixed now though!
