### ISSUE TITLE
requirements are missing from setup.py

### ISSUE THREAD

**Issue by jlec** [rasbt/biopandas#2]
As far as I can see there are no requirements listed in ```setup.py```. At least pandas should be needed.

**Comment by rasbt** [comment]
Thanks for the note. I wasn't sure if pandas will be automatically installed if I put something like
`install_requires=['pandas>=0.17.0'],` into the `setup.py` file -- I don't want to force people to install pandas from PyPI (vs. e.g., Anaconda/Miniconda); but I guess it will only be installed if someone runs `pip install biopandas -r`. Will test this out on https://testpypi.python.org/pypi and add it to the setup.py.

**Comment by rasbt** [comment]
Alright, requirements should be included in the next PyPI version (a8375cfa7ffa30fa4b67308eeb46d40b8aaeab57)
