### ISSUE TITLE
Please ship tests to pypi

### ISSUE THREAD

**Issue by jlec** [rasbt/biopandas#3]
Downstream distro maintainers love to test during packaging. Please included the test suite in the pypi tarball so that we can test during packaging.

**Comment by rasbt** [comment]
Sure, I didn't want to "bloat" the PyPI package, but I will add the tests if this is a desired "feature" :)

**Comment by rasbt** [comment]
Also here, tests will be part of the next PyPI release (a8375cfa7ffa30fa4b67308eeb46d40b8aaeab57)
