### ISSUE TITLE
What's up next?

### ISSUE THREAD

**Issue by timini** [rasbt/biopandas#4]
Hey,

Love pandas, would like to contribute.

what's on the todo?

**Comment by rasbt** [comment]
That's nice to hear, thanks! I am actually also quite busy in the machine learning community, and it would be great if someone would help me adding more features :). I will add a few "enhancements" I have on my todo list to the issue tracker.

**Comment by rasbt** [comment]
Alright, I added a few todo's to the issue tracker, feel free to pick!
