### ISSUE TITLE
Documentation links are 404 missing

### ISSUE THREAD

**Issue by chendaniely** [rasbt/biopandas#61]
Only the `home` and `installation` pages do not have 404 errors. 
The `tutorials`, `api`, `changelog`, etc are all giving me 404 errors, e.g.,

http://rasbt.github.io/biopandas/tutorials/Working_with_PDB_Structures_in_DataFrames/tutorials/Working_with_PDB_Structures_in_DataFrames/

**Comment by rasbt** [comment]
Thanks for the note, it looks like the address chunk "tutorials/Working_with_PDB_Structures_in_DataFrames/" appears twice in the URL link. May have happened due to some mkdocs update. Will fix it

**Comment by rasbt** [comment]
should be fixed now!
