### ISSUE TITLE
PDB link on rcsb has changed

### ISSUE THREAD

**Issue by luc-j-bourhis** [rasbt/biopandas#66]
The method `_fetch_pdb` uses the template `http://www.rcsb.org/pdb/files/%s.pdb` but RCSB seems to use `https://files.rcsb.org/download/%s.pdb` now.

**Comment by rasbt** [comment]
Thanks for the note, I appreciate it. I am going to fix that now.

**Comment by rasbt** [comment]
FYI: Both links seem to work, but I am going to change to the newer (your suggested) one
