### ISSUE TITLE
Biopandas cannot open ent.gz

### ISSUE THREAD

**Issue by gezmi** [rasbt/biopandas#81]
Hi! 

I have a problem with opening gzipped PDB files. We have a local copy of the PDB, downloaded in the `ent.gz` format, as they provide it. However, biopandas since a commit on 22nd October throws an error of:
`"Wrong file format; allowed file formats are .pdb and .pdb.gz."`
Since this is the filename provided by PDB, it would be nice to get it open without renaming/gzipping.

I have two prposed solutions:
Either only check for .gz, or inlcude an other elseif for ent.gz
Alternatively, providing  a way to parse a PDB file from handle could also work.

Thank you!

**Comment by rasbt** [comment]
Thanks for the note! I think we added this to improve the error messages, but yeah, that's an issue. One solution could be just changing it to `.gz`, but then i am a bit worried that users who are not aware of the limitation that the tool only works with pdb files will encounter other cryptic error messages again ...

Alternatively, maybe adding `ent.gz` could be an option. I think `.ent` and  `.ent.gz` are common extensions so adding them makes sense.

**Comment by rasbt** [comment]
Just modified the code to allow .ent and .ent.gz files. I am not making a new version release right away, but to install the development version in the mean time you can install it via

    pip install git+git://github.com/rasbt/biopandas.git

**Comment by gezmi** [comment]
Thank you!
