### ISSUE TITLE
Latest conda-forge release 0.2.7 instead of 0.2.8?

### ISSUE THREAD

**Issue by dominiquesydow** [rasbt/biopandas#86]
#### Describe the bug

Hi!

Thank you for cutting a new release v0.2.8 on GH!
https://github.com/rasbt/biopandas/releases/tag/v0.2.8 

As far as I understand, you also cut a new release on `conda-forge`, right?
https://github.com/conda-forge/biopandas-feedstock/pull/12

However, when installing `biopandas` via `conda-forge` I only retrieve version 0.2.7. 
Could you please check if you run into the same issue?

#### Steps/Code to Reproduce

```
conda create -n biopandas biopandas
conda activate biopandas
conda list biopandas
```

#### Expected Results

`biopandas` 0.2.8 installation.

#### Actual Results

`biopandas` 0.2.7 installation.

```
# Name                    Version                   Build  Channel
biopandas                 0.2.7              pyh9f0ad1d_1    conda-forge
```

If I ask for 0.2.8 directly
```
conda install biopandas=0.2.8
```
I get
```
PackagesNotFoundError: The following packages are not available from current channels:

  - biopandas=0.2.8

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

#### Versions

```
>>> import biopandas; print("biopandas", biopandas.__version__)
biopandas 0.2.7
>>> import platform; print(platform.platform())
Linux-4.15.0-154-generic-x86_64-with-glibc2.10
>>> import sys; print("Python", sys.version)
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0]

# conda install scikit-learn numpy scipy -y
>>> import sklearn; print("Scikit-learn", sklearn.__version__)
Scikit-learn 0.24.2
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.21.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
```

**Comment by rasbt** [comment]
Hi there!  Thanks for opening this issue. Trying to install it from conda-forge, I am getting exactly the same issue. My initial guess is that's because Python 3.8 & 3.9 are not explicitly specified in the setup.py file. I am guessing that you are probably also using one of these two more recent versions of Python.

I will make a new Biopandas release with the updated setup.py and see if that solves the issue.

**Comment by dominiquesydow** [comment]
@rasbt, wonderful, thank you very much!
