### ISSUE TITLE
Implement CIF and mmCIF format support for large biological assemblies

### ISSUE THREAD

**Issue by rasbt** [rasbt/biopandas#93]
### Discussed in https://github.com/rasbt/biopandas/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **rjboyd00** March  6, 2022</sup>

> Word on the street is that the PDB is moving towards the mmCIF file format as the primary file format in the future and it would be great to have support for a pythonic way to interact with these file formats that plays well with large structures. </div>

As discussed in #92, it would be nice to add a `PandasCIF`/`PandasMmCIF` (analogous to `PandasPdb`) class to support the new file format.

**Comment by a-r-j** [comment]
I think this can be closed :)

**Comment by rasbt** [comment]
Yup :)
