### ISSUE TITLE
Get Carbon Method in PandasPDB

### ISSUE THREAD

**Issue by a-r-j** [rasbt/biopandas#95]
#### Describe the bug
Hiya, just wanted to check in if [this is the intended behaviour](https://github.com/rasbt/biopandas/blob/6fb3d310d6b2327c2200651bd6269c909263f76f/biopandas/pdb/pandas_pdb.py#L359)

```python
    @staticmethod
    def _get_carbon(df, invert):
        """Return c-alpha atom entries from a DataFrame"""
        if invert:
            return df[df["element_symbol"] == "C"]
        else:
            return df[df["element_symbol"] != "C"]
```

I think the cases should be switched; `invert=True` grabs the `"C"` entries, whereas `invert=False` grabs the non-carbon entries.

If this is a bug I'll submit a PR

**Comment by rasbt** [comment]
Good catch! Yeah, I do think it's doing the opposite of what it's supposed to do.
